# Generated by Django 5.0.2 on 2024-07-11 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0014_alter_user_email'),
        ('universitie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customuser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('auth_provider', models.CharField(default='email', max_length=50)),
                ('fathername', models.CharField(default=None, max_length=20, null=True)),
                ('mothername', models.CharField(default=None, max_length=20, null=True)),
                ('phone', models.IntegerField(null=True, unique=True)),
                ('idNumber', models.IntegerField(default=None, null=True)),
                ('idNationalNumber', models.IntegerField(default=None, null=True, unique=True)),
                ('faculty', models.CharField(default=None, max_length=20, null=True)),
                ('section', models.CharField(default=None, max_length=20, null=True)),
                ('city', models.CharField(default=None, max_length=20, null=True)),
                ('year', models.IntegerField(default=None, null=True)),
                ('typeJob', models.CharField(default=None, max_length=10, null=True)),
                ('img', models.CharField(default=None, max_length=200, null=True)),
                ('status', models.CharField(default='غير مسجل في السكن', max_length=20, null=True)),
                ('job', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff')], default='student', max_length=10, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.room')),
                ('unitNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit')),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.universitie')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('idNationalNumber', models.IntegerField(default=None, null=True, unique=True)),
                ('year', models.IntegerField(default=None, null=True)),
                ('typeJob', models.CharField(default=None, max_length=10, null=True)),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.universitie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=None, max_length=255, null=True, unique=True)),
                ('first_name', models.CharField(default=None, max_length=100, null=True)),
                ('last_name', models.CharField(default=None, max_length=100, null=True)),
                ('phone', models.CharField(default=None, max_length=15, null=True)),
                ('idNationalNumber', models.IntegerField(default=None, null=True, unique=True)),
                ('faculty', models.CharField(default=None, max_length=20, null=True)),
                ('section', models.CharField(default=None, max_length=20, null=True)),
                ('year', models.IntegerField(default=None, null=True)),
                ('status', models.CharField(default='غير مسجل في السكن', max_length=20, null=True)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students_in_room', to='universitie.room')),
                ('unitNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit')),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.universitie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNationalNumber', models.IntegerField(default=None, null=True, unique=True)),
                ('attachments', models.FileField(upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/')),
                ('payment_method', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='في انتظار الموافقة', max_length=20)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests_for_room', to='universitie.room')),
                ('unitNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit')),
                ('university', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.universitie')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
