# Generated by Django 5.0.2 on 2024-07-17 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_student_options'),
        ('universitie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='unitNumber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.DateField(default=None, null=True),
        ),
    ]
