# Generated by Django 5.0.2 on 2024-07-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_staff_unitnumber_alter_staff_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='year',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(default=None, null=True),
        ),
    ]
