# Generated by Django 5.0.7 on 2024-07-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_customuser_year_alter_staff_year_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'مستخدم', 'verbose_name_plural': 'المستخدمين'},
        ),
        migrations.AlterModelOptions(
            name='registrationrequest',
            options={'verbose_name': 'طلبات التسجيل في السكن', 'verbose_name_plural': 'طلبات التسجيل في السكن'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'الموظفين', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
    ]
