# Generated by Django 5.0.7 on 2024-08-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationrequest',
            name='attachments',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='Face_picture',
            field=models.FileField(default=None, upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='Front_face',
            field=models.FileField(default=None, upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/'),
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='back_face',
            field=models.FileField(default=None, upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/'),
        ),
    ]
