# Generated by Django 5.0.7 on 2024-08-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_customuser_notification_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='img',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='Face_picture',
            field=models.FileField(blank=True, default=None, null=True, upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='Front_face',
            field=models.FileField(blank=True, default=None, null=True, upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/'),
        ),
        migrations.AlterField(
            model_name='registrationrequest',
            name='back_face',
            field=models.FileField(blank=True, default=None, null=True, upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/'),
        ),
    ]
