# Generated by Django 5.0.7 on 2024-10-20 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_alter_customuser_city_alter_customuser_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
