# Generated by Django 5.0.7 on 2024-10-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_staff_year_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='year',
            field=models.DateField(),
        ),
    ]
