# Generated by Django 5.0.2 on 2024-03-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_customuser_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_email_verified',
        ),
    ]
