# Generated by Django 5.0.2 on 2024-03-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_user_onetimepassword_delete_customuser'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0014_alter_user_email'),
        ('authtoken', '0003_tokenproxy'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customuser',
        ),
    ]
