# Generated by Django 5.0.2 on 2024-05-07 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_rooms_unites_univesities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
        migrations.RenameModel(
            old_name='Univesities',
            new_name='Unite',
        ),
        migrations.DeleteModel(
            name='Unites',
        ),
        migrations.RenameField(
            model_name='unite',
            old_name='name',
            new_name='unites',
        ),
    ]
