# Generated by Django 5.0.2 on 2024-05-07 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_rename_rooms_room_rename_univesities_unite_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Unite',
        ),
    ]
