# Generated by Django 5.0.2 on 2024-05-12 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_delete_room_delete_unite'),
        ('universitie', '0008_rename_number_unit_unit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='roomNumber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.room'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='unitNumber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.universitie'),
        ),
    ]
