# Generated by Django 5.0.2 on 2024-05-12 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_student'),
        ('universitie', '0008_rename_number_unit_unit_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fathername',
            new_name='faculty',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mothername',
            new_name='section',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='roomNumber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.room'),
        ),
        migrations.AddField(
            model_name='student',
            name='unitNumber',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit'),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.universitie'),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
