# Generated by Django 5.0.2 on 2024-05-12 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_rename_fathername_student_faculty_and_more'),
        ('universitie', '0008_rename_number_unit_unit_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roomNumber',
        ),
        migrations.AddField(
            model_name='student',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='universitie.room'),
            preserve_default=False,
        ),
    ]
