# Generated by Django 5.0.2 on 2024-05-13 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_remove_student_roomnumber_student_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='roomNumber',
            new_name='room',
        ),
    ]
