# Generated by Django 5.0.2 on 2024-07-14 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countOfBread', models.IntegerField(default=None, null=True)),
                ('rule', models.IntegerField(default=None, null=True)),
                ('numberOfRequest', models.IntegerField(default=None, null=True)),
                ('status', models.CharField(default='لم يتم الاستلام بعد', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
