# Generated by Django 5.0.2 on 2024-07-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreadOrder',
            fields=[
                ('bread_ties', models.IntegerField(default=None, null=True)),
                ('order_number', models.AutoField(primary_key=True, serialize=False)),
                ('rule', models.IntegerField()),
                ('status', models.CharField(choices=[('لم يتم الاستلام بعد', 'لم يتم الاستلام بعد'), ('تم التسليم', 'تم التسليم')], default='لم يتم الاستلام بعد', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
        migrations.DeleteModel(
            name='RequestBread',
        ),
    ]
