# Generated by Django 5.0.2 on 2024-07-15 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_email_verification_code'),
        ('service', '0002_breadorder_delete_requestbread'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequest',
            fields=[
                ('attachments', models.FileField(upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/')),
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('في انتظار الموافقة', 'في انتظار الموافقة'), ('تمت الموافقة', 'تمت الموافقة'), ('تم الرفض', 'تم الرفض')], default='في انتظار الموافقة', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
