# Generated by Django 5.0.2 on 2024-07-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_jobrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='finishTime',
            field=models.TimeField(null=True),
        ),
    ]
