# Generated by Django 5.0.2 on 2024-07-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_customuser_temporary_data'),
        ('service', '0004_jobrequest_finishtime'),
        ('universitie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('Fail_description', models.TextField()),
                ('Fail_photo', models.FileField(upload_to='C:/Users/Administrator/Desktop/Django-project/venv/subject/account/attachments/')),
                ('request_number', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('طلب جديد', 'طلب جديد'), ('ستتم معالجته', 'ستتم معالجته')], default='طلب جديد', max_length=20)),
                ('room', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fail_in_room', to='universitie.room')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('unitNumber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='universitie.unit')),
            ],
        ),
    ]
