# Generated by Django 5.0.7 on 2024-07-18 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_maintenancerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breadorder',
            options={'verbose_name_plural': 'طلبات الخبز'},
        ),
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'verbose_name': 'طلبات اذن العمل', 'verbose_name_plural': 'طلبات اذن العمل'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'verbose_name_plural': 'طلبات الاعطال'},
        ),
    ]
