# Generated by Django 5.0.7 on 2024-08-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_notification_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'الاشعار', 'verbose_name_plural': 'الاشعارات'},
        ),
    ]
