# Generated by Django 5.0.2 on 2024-05-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitie', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Univesitie',
            new_name='Universitie',
        ),
    ]
