# Generated by Django 5.0.2 on 2024-05-12 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitie', '0003_unit_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='unit',
            name='number',
            field=models.CharField(max_length=30),
        ),
    ]
