# Generated by Django 5.0.2 on 2024-05-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitie', '0004_alter_room_number_alter_unit_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='universitie',
            new_name='universitie_name',
        ),
    ]
