# Generated by Django 5.0.2 on 2024-05-12 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitie', '0005_rename_universitie_unit_universitie_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversitySearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=100)),
            ],
        ),
    ]
