# Generated by Django 5.0.2 on 2024-05-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitie', '0006_universitysearchrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='universitie_name',
            new_name='university_name',
        ),
    ]
