# Generated by Django 5.0.2 on 2024-05-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitie', '0007_rename_universitie_name_unit_university_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='number',
            new_name='Unit_name',
        ),
    ]
